(function(){
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fd=v=>{if(!v)return 'A INFORMAR';const p=String(v).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:String(v)};
const longDate=v=>{if(!v)return 'A INFORMAR';const [y,m,d]=String(v).split('-');const meses=['JANEIRO','FEVEREIRO','MARÇO','ABRIL','MAIO','JUNHO','JULHO','AGOSTO','SETEMBRO','OUTUBRO','NOVEMBRO','DEZEMBRO'];return `${d} DE ${meses[(+m)-1]||''} DE ${y}`};
const brand=()=>'<div class="hs-brand"><div class="hs-symbol"><span class="hs-ring a"></span><span class="hs-ring b"></span><span class="hs-word">HS</span></div><div class="hs-beyond">beyond<br>solutions</div></div>';
const wm=()=>'<div class="hs-wm"></div>';
const footer=n=>`<div class="hs-footer"><div class="hs-footmark"></div><div class="hs-foottext">Matriz - Rua XV de novembro 1336, salas 34 e 35 – Blumenau – SC – CEP 89010-903<br>www.horizonservitas.com +55 47 3326-1844</div><div class="hs-pageno">${n} de 5</div></div>`;
const page=(inner,n)=>`<section class="hs-page">${brand()}${wm()}${inner}${footer(n)}</section>`;
const instTable=a=>{const rows=(a||[]).map(x=>`<tr><td>${esc(x.num)}</td><td>${esc(x.year)}</td><td>${esc(x.dim)}</td><td>${esc(x.cap)}</td><td>${esc(x.state)}</td></tr>`).join('');return `<table class="hs-table"><thead><tr><th>Número</th><th>Ano de<br>Construção</th><th>Dimensões<br>(metros)</th><th>Capacidade</th><th>Estado de<br>Conservação</th></tr></thead><tbody>${rows||'<tr><td colspan="5">A INFORMAR</td></tr>'}</tbody></table>`};
const damageList=a=>{const rows=(a||[]).map(x=>`<li>${esc(x.qty||'')} ${esc(x.unit||'')} ${esc(x.desc||'')}${x.age?' – '+esc(x.age):''}</li>`).join('');return `<ul class="hs-damage-list">${rows||'<li>A INFORMAR</li>'}</ul>`};
function data(){try{return typeof vals==='function'?vals():{}}catch(e){return {}}}
function buildPages(){const d=data();const p1=`<div class="hs-title">ATA DE VISTORIA</div><div class="hs-subtitle">RISCOS NOMEADOS EMPRESARIAL</div><div class="hs-claimnums"><div class="r"><span>Sinistro Seguradora:</span><b>A INFORMAR</b></div><div class="r"><span>Sinistro Horizon Servitas:</span><b>${esc(d.sinistro||'A INFORMAR')}</b></div></div><div class="hs-meta"><div class="row"><b>COMPANHIA SEGURADORA:</b><span>A INFORMAR</span></div><div class="row"><b>SEGURADO:</b><span>A INFORMAR</span></div><div class="row"><b>COOPERADO:</b><span>${esc(d.segurado||'A INFORMAR')}</span></div><div class="row"><b>LOCAL DO SINISTRO:</b><span>${esc(d.endereco||'A INFORMAR')}</span></div><div class="row"><b>APÓLICE DE SEGUROS:</b><span>A INFORMAR</span></div><div class="row"><b>PRODUTO:</b><span>RISCOS NOMEADOS</span></div><div class="row"><b>CORRETOR:</b><span>A INFORMAR</span></div><div class="row"><b>DATA DO SINISTRO:</b><span>${longDate(d.dataSinistro)}</span></div><div class="row"><b>COBERTURA RECLAMADA:</b><span>A INFORMAR</span></div></div>`;
const p2=`<div class="hs-section">1 &nbsp; PROPRIEDADE RURAL RECLAMADA</div><p class="hs-text">Trata-se de propriedade rural vistoriada e situada em ${esc(d.endereco||'local a informar')}${d.coords?' – coordenadas '+esc(d.coords):''}.</p>${instTable(d.inst)}<div class="hs-small hs-muted" style="margin-top:8mm;text-align:center">Figura / imagem da propriedade poderá ser inserida em etapa posterior.</div>`;
const p3=`<div class="hs-section">2 &nbsp; DESCRIÇÃO DA OCORRÊNCIA PELO COOPERADO</div><p class="hs-text">${esc(d.relato||'A INFORMAR')}</p><div class="hs-section">3 &nbsp; APURAÇÕES DA REGULAÇÃO</div><div class="hs-subsection">3.1 &nbsp; LEVANTAMENTOS EM VISTORIA</div><p class="hs-text">${esc(d.constatacoes||'A INFORMAR')}</p><div class="hs-subsection" style="margin-top:8mm">RELAÇÃO DE DANOS:</div>${damageList(d.damage)}`;
const no=d.outroSeguro==='nao',yes=d.outroSeguro==='sim';
const p4=`<div class="hs-subsection" style="margin-top:12mm">3.2 &nbsp; LEVANTAMENTOS DOCUMENTAIS</div><p class="hs-text">${esc(d.documentos||'Não foram coletados documentos em vistoria.')}</p><div class="hs-section">4 &nbsp; DECLARAÇÃO SOBRE OUTROS SEGUROS</div><p class="hs-text">Para prestar a referida declaração, assinale uma das opções conforme abaixo:</p><div class="hs-checkrow"><span class="hs-box">${no?'X':''}</span><span>Declaro que <b>não existe</b> outra apólice de seguro que conceda cobertura ao(s) mesmo(s) bem(ns) amparado(s) pela apólice acima referenciada.</span></div><div class="hs-checkrow"><span class="hs-box">${yes?'X':''}</span><span>Declaro que <b>existe(m)</b> outra(s) apólice(s) de seguro que conceda(m) cobertura(s) ao(s) mesmo(s) bem(ns) amparado(s) pela apólice em questão.</span></div><p class="hs-text">Assumo ainda integral responsabilidade pela presente declaração e suas consequências, sob pena da perda de qualquer direito à indenização, caso exista outro seguro não declarado neste documento.</p><div class="hs-section" style="margin-top:8mm">5 &nbsp; CRONOLOGIA</div><table class="hs-chrono"><tr><td>Data da ocorrência</td><td>${fd(d.c1||d.dataSinistro)}</td></tr><tr><td>Data do aviso</td><td>${fd(d.c2)}</td></tr><tr><td>Data da solicitação de vistoria</td><td>${fd(d.c3)}</td></tr><tr><td>Data do Agendamento da vistoria</td><td>${fd(d.c4)}</td></tr><tr><td>Data da vistoria</td><td>${fd(d.c5)}</td></tr></table>`;
const p5=`<div class="hs-section" style="margin-top:12mm">6 &nbsp; INFORMAÇÕES COMPLEMENTARES</div><p class="hs-text">As orientações não representam o reconhecimento prévio de cobertura do sinistro ora reclamado ou de eventual valor a indenizar, os quais dependem da análise das Condições do Seguro contratado e da devida análise e manifestação da Companhia Seguradora.</p><div class="hs-date-line">${esc(d.cidadeEmissao||'Blumenau (SC)')}, ${d.c5?fd(d.c5):fd(d.dataSinistro)}.</div><div class="hs-sig"><div class="hs-sigline">Regulador</div><div style="text-align:center;margin-top:3mm">${esc(d.regulador||'A INFORMAR')}</div><div style="text-align:center;margin-top:2mm">CPF: ${esc(d.cpfReg||'A INFORMAR')}</div></div><div class="hs-sig2"><div class="hs-sigline">Segurado / Representante</div><div style="text-align:center;margin-top:3mm">${esc(d.representante||d.segurado||'A INFORMAR')}</div><div style="text-align:center;margin-top:2mm">CPF: ${esc(d.cpfRep||d.cpfCnpj||'A INFORMAR')}</div></div>`;
let h=document.getElementById('printHost');if(!h){h=document.createElement('div');h.id='printHost';document.body.appendChild(h)}h.innerHTML=page(p1,1)+page(p2,2)+page(p3,3)+page(p4,4)+page(p5,5);return h.innerHTML}
window.printHS=function(){try{if(typeof saveDraft==='function')saveDraft()}catch(e){}buildPages();setTimeout(()=>window.print(),80)};
window.exportWord=async function(){const pages=buildPages();let css='';try{css=await (await fetch('./v7_4.css?v=74',{cache:'no-store'})).text()}catch(e){}const html='<!DOCTYPE html><html><head><meta charset="UTF-8"><style>'+css+' @page{size:A4;margin:0}#printHost{display:block!important}</style></head><body><div id="printHost">'+pages+'</div></body></html>';const file=new File(['\ufeff',html],'ata_vistoria_HS_V7_4.doc',{type:'application/msword'});if(navigator.canShare&&navigator.canShare({files:[file]})){try{await navigator.share({files:[file],title:'Ata de Vistoria HS'});return}catch(e){if(e&&e.name==='AbortError')return}}const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=file.name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove()},4000)};
function patch(){const badge=document.querySelector('.badge');if(badge)badge.textContent='V7.4';const helper=document.querySelector('.head .helper');if(helper)helper.textContent='HS — formulário integrado + emissão A4';const buttons=[...document.querySelectorAll('button')];const pdf=buttons.find(b=>/Exportar\s*\/\s*Salvar PDF/i.test(b.textContent));if(pdf){pdf.setAttribute('onclick','printHS()');pdf.textContent='Exportar / Salvar PDF — padrão HS'}const word=buttons.find(b=>/Exportar Word/i.test(b.textContent));if(word){word.setAttribute('onclick','exportWord()');word.textContent='Exportar Word editável — iPhone'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(patch,100));else setTimeout(patch,100);
})();